### ISSUE TITLE
Blinking cursor and exiting

### ISSUE THREAD

**Issue by livibetter** [pauis/pipong#1]
I didn't realize at first when I saw the ball sometimes was 1-char, otherwise 2-char. It turns out the second one was _the blinking cursor_.

It should be able to be resolved with `^[[?25l` / `^[[?25h`, from `urxvt(7)`:

```
"Pm = 25" (DECTCEM)
    h   Visible cursor {cnorm/cvvis}
    l   Invisible cursor {civis}
```

About the _exiting_, which seems to be a bit of less elegant, the shell prompt reappeared right after the URL in the title screen, which is just a middle of lines.

A quick fix is using `sout.Clear()`, but a better one is to save and restore using `1049`, that is:

```
"Pm = 1047" (X11 XTerm alternate screen buffer)
    h   Use Alternate Screen Buffer
    l   Use Normal Screen Buffer - clear Alternate Screen Buffer if returning from it
"Pm = 1048" (X11 XTerm alternate DECSC)
    h   Save cursor position
    l   Restore cursor position
"Pm = 1049" (X11 XTerm 1047 + 1048)
    h   Use Alternate Screen Buffer - clear Alternate Screen Buffer if switching to it
    l   Use Normal Screen Buffer
```

I'd open a PR, but I don't really sure where I should put these codes in. I thought about the constructor and destructor `Sin`, but that doesn't sound quite right, so I am creating this issue.

By the way, maybe `SOut::Clear()` should use escape codes (erase display/move cursor) instead of making `system()` call.

**Comment by djlim7** [comment]
Thank you. I really appreciate your help. I will check the problems and fix them.

**Comment by djlim7** [comment]
First, I fixed blinking cursor. (75022b9) Now `^[[?25l` is automatically called when the constructor of SOut is called at first, and `^[[?25h` is for the last destructor.

**Comment by livibetter** [comment]
@pauis Good, I can see it's fixed now. One down, one to go.

**Comment by djlim7** [comment]
`1049` was used to switch buffers, and `Ps J` was used to replace `system("clear")`.

```
"ESC [ Ps J"
Erase in Display ( ED )
```

But `1049` don't do their work at some devices (e.g. Raspberry Pi bash), so I'll locate the cursor end of the screen so that all command prompt print the exiting more appropriately. I'm working on it.
